obj-$(CONFIG_HUAWEI_CHARGER)      += huawei_battery.o
obj-$(CONFIG_HUAWEI_CHARGER)      += huawei_battery_vote.o
obj-$(CONFIG_HUAWEI_CHARGER)      += huawei_charger.o
obj-$(CONFIG_HUAWEI_BUCK_CHARGER) += huawei_buck_charger.o
obj-$(CONFIG_HUAWEI_BUCK_CHARGER) += huawei_buck_common.o
obj-$(CONFIG_HUAWEI_BUCK_CHARGER) += charging_core.o
