ccflags-y := -I$(srctree)/techpack/display/msm
ccflags-y += -I$(srctree)/techpack/display/msm/sde
ccflags-y += -I$(srctree)/techpack/display/msm/dp
ccflags-y += -I$(srctree)/techpack/display/include
ccflags-y += -I$(srctree)/techpack/display/include/uapi/display
ccflags-y += -I$(srctree)/include/drm

obj-y += dp_interface.o