obj-$(CONFIG_HUAWEI_VIBRATOR) += aw86907/
obj-$(CONFIG_HUAWEI_VIBRATOR) += aw01624/
obj-$(CONFIG_HUAWEI_VIBRATOR) += aw_vibrator/
obj-$(CONFIG_HUAWEI_VIBRATOR) += vibrator_event.o
obj-$(CONFIG_HUAWEI_PMI_LDO_VIBRATOR) += pmi_ldo_vibrator/
