obj-$(CONFIG_POWER_AVS)		+= avs/
obj-$(CONFIG_POWER_RESET)	+= reset/
obj-$(CONFIG_POWER_SUPPLY)	+= supply/
obj-$(CONFIG_HUAWEI_CHARGER)	+= charger/
obj-$(CONFIG_POWER_DUBAI)	+= dubai/
obj-$(CONFIG_HUAWEI_ADC)       += huawei_adc/

