#
#easy-shell Makefile
#
obj-$(CONFIG_DFX_ECALL) += easy_shell.o
ccflags-y += -Wextra \
             -Wdate-time \
             -Wfloat-equal \
             -Wno-shadow \
             -Wno-unused-parameter \
             -Wno-sign-compare \
             -Wformat=2