#=============================================================================
#  wifi
#=============================================================================
obj-$(CONFIG_WIFI_DELAY_STATISTIC) += ipv4/wifi_delayst.o
obj-$(CONFIG_HW_WIFI) += ipv4/
obj-$(CONFIG_HW_BOOSTER) += booster/
obj-y += hwril/
obj-y += hwril_sim_sd/
obj-$(CONFIG_CHR_NETLINK_MODULE) += chr/
obj-$(CONFIG_HW_DC_MODULE) += hw_dual_connection/
obj-$(CONFIG_HW_DPIMARK_MODULE) += hw_dpi_mark/
obj-$(CONFIG_HW_WAUDIO_MODULE) += waudio/
obj-$(CONFIG_HW_WIFI_EXT) += wifi_ext_adaptor/
obj-$(CONFIG_HW_RSMC) += rsmc/
obj-$(CONFIG_HW_RSMC) += rsmc_x801/
obj-$(CONFIG_HW_NETWORK_DCP) += network_dcp/
EXTRA_CFLAGS += -Idriver/huawei_platform
