obj-$(CONFIG_LCD_KIT_CROP) += lcd_kit_crop.o

EXTRA_CFLAGS += \
	-I$(srctree)/drivers/devkit/lcdkit/lcdkit3.0/kernel/qcom/common/include \
	-I$(srctree)/drivers/devkit/lcdkit/lcdkit3.0/kernel/qcom/include \
	-I$(srctree)/techpack/display/msm \
	-I$(srctree)/techpack/display/msm/dsi \
	-I$(srctree)/techpack/display/include \
	-I$(srctree)/techpack/display/include/uapi/display \
	-I$(srctree)/include/drm \
	-I$(srctree)/../../vendor/huawei/extra/kernel/drivers/sensor/ext_inputhub/matting_algo_task