# Switch Class Driver
obj-$(CONFIG_SWITCH_FSA9685) += switch_fsa9685.o
obj-$(CONFIG_SWITCH_FSA9685) += usbswitch_fsa9685.o
obj-$(CONFIG_SWITCH_FSA9685) += usbswitch_rt8979.o
obj-$(CONFIG_SWITCH_FSA9685) += rt8979_bc12.o
obj-$(CONFIG_SWITCH_FSA9685) += switch_chip_i2c.o