#
# Huawei memory direct reclaim monitor configuration
#
ccflags-$(CONFIG_HW_RECLAIM_ACCT) += -Wframe-larger-than=4096
obj-$(CONFIG_HW_RECLAIM_ACCT) += reclaim_acct.o
obj-$(CONFIG_HW_RECLAIM_ACCT) += reclaimacct_show.o
