# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_HUAWEI_CHARGER) += buck_charge.o
obj-$(CONFIG_HUAWEI_CHARGER_AP) += buck_charge.o
obj-$(CONFIG_HUAWEI_CHARGER) += buck_charge_jeita.o
obj-$(CONFIG_HUAWEI_CHARGER_AP) += buck_charge_jeita.o
obj-$(CONFIG_HUAWEI_CHARGER) += buck_charge_vote.o
obj-$(CONFIG_HUAWEI_CHARGER_AP) += buck_charge_vote.o