subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/typec/tcpc/inc
subdir-ccflags-y += -I$(srctree)/drivers/devkit/audiokit
obj-$(CONFIG_HUAWEI_PD) += hw_pd.o
obj-$(CONFIG_HUAWEI_PD_THIRDPARTY) += hw_pd_thirdparty.o
obj-$(CONFIG_TCPC_RT1711H) += richtek/
ifeq ($(TARGET_PRODUCT),bengal)
ccflags-y += -DQCOM_PLATFORM_6225
endif
