obj-$(CONFIG_LCD_KIT_HYBRID) += huawei_ts_kit_hybrid_core.o
obj-$(CONFIG_LCD_KIT_HYBRID) += hybrid_keypad.o
EXTRA_CFLAGS += \
	-I$(srctree)/drivers/devkit/lcdkit/lcdkit3.0/kernel/qcom/src/hybrid \
	-I$(srctree)/drivers/devkit/tpkit/3_0 \
	-I$(srctree)/drivers/devkit/lcdkit/lcdkit3.0/kernel/qcom/common/include \
	-I$(srctree)/drivers/huawei_platform/sensor/ext_inputhub/default/

