/* SPDX-License-Identifier: GPL-2.0 */
/*
 * lcd_kit_hybrid_swctrl.h
 *
 * head file for switch control
 *
 * Copyright (c) 2022-2022 Huawei Technologies Co., Ltd.
 *
 * This software is licensed under the terms of the GNU General Public
 * License version 2, as published by the Free Software Foundation, and
 * may be copied, distributed, and modified under those terms.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 */
#ifndef __LCD_KIT_HYBRID_SWCTRL_H_
#define __LCD_KIT_HYBRID_SWCTRL_H_
#include <linux/types.h>

/* hybrid switch interface */
struct hybrid_sw_ops {
	int (*request_sync)(struct hybrid_sw_ops *ops, int value);
	bool (*sw_status_check)(struct hybrid_sw_ops *ops);
	int (*send_hybrid_state)(struct hybrid_sw_ops *ops, u8 state);
};

/* the callback function when get switch irq */
typedef void (*switch_work_handle)(int sw_state, int req_state);

/*
 * initialize for a type of hybrid switch
 * @param handle switch irq callback handle
 * @param ctrl_name the name for the switch
 * @return NULL for failure, otherwise get the switch API object
 */
struct hybrid_sw_ops *hybrid_swctrl_init(switch_work_handle handle, const char *ctrl_name);

/*
 * release for a hybrid switch
 * @param sw_ops the switch API object generated by hybrid_swctrl_init
 */
void hybrid_swctrl_release(struct hybrid_sw_ops *sw_ops);

#endif
