# SPDX-License-Identifier: GPL-2.0

#obj-$(CONFIG_BLACKBOX_PLATFORM)  += system_adapter.o
obj-y  += system_adapter.o rainbow_mod.o blackbox_subsystem.o
obj-$(CONFIG_DFX_RAINBOW_TRACE) += rainbow_trace.o
obj-$(CONFIG_DFX_RAINBOW_HIMNTN) += rainbow_himntn.o
